Pull Request for Branch "sideB" to master branch after successful project completion
jkanyi-web/Microverse_Portfolio pull request #1
Opened 2022-12-02 17:33 UTC by jkanyi-web

- Added a gitignore file
- Added descriptive README file.
- Added node_modules into the gitignore file
- Set up a [linter for HTML and CSS](https://github.com/microverseinc/linters-config)
- Added .html file
- Added .css file
- Added additional linter files

2022-12-02 18:16 UTC, Tadesse-Alemayehu requested changes
### Hi @jkanyi-web 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![EquatorialVictoriousBlackpanther-size_restricted](https://user-images.githubusercontent.com/69077061/204090500-5512fd84-cfd9-4aee-9d5d-8ee90740a92d.gif)

## Highlights
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 18:16 UTC, TadesseDev commented on index.html
> +    </div>
- [ ] Good job @jkanyi-web on the overall design, But here we need to use a `header` tag for the reader section. Typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.
- [ ] Please Also don't forget to add the `hamburger `icon to the right of the screen with a `nav `tag.
- [ ] One more thing here is the font, please remember the font here is `Roboto`.

2022-12-02 18:16 UTC, TadesseDev commented on index.html
> +            <div class="normalbutton"></div>
- [ ] Dear @jkanyi-web, It would be wise to use an `a` tag for your logo. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-12-02 18:16 UTC, TadesseDev commented on index.html
> +        </div>
- [ ] Dear @jkanyi-web, We don't need this part of the design, This is only for the Figma design and should be part of the phone where your website is going to be displayed. This is  `NOT PART OF YOUR DESIGN`

2022-12-02 18:16 UTC, TadesseDev commented on index.html
> +    <div class="headline">
- [ ] Dear @jkanyi-web, this` div `tag better be replaced with a `section` tag for a semantic reason. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +    </div>
- [ ] Dear @jkanyi-web, good job adding the background, yet it is not as it looks on the Figma design. Please update this.

### Figma background
![background2](https://user-images.githubusercontent.com/69077061/205356752-dac9857c-1b27-40d0-8224-7af4654e1173.PNG)
### Your background
![background](https://user-images.githubusercontent.com/69077061/205356744-1b57bfa5-74b3-4d48-bb42-2eb3aff372d3.PNG)

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +        <div class="primarytext">Hey There, I'm Kanyi</div>
- [ ] Dear @jkanyi-web, for semantic reason please use `h1` tag for the `Hey There, I'm Kanyi` text.

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +        <div class="supportingtext">I'm a software developer.</div>
Dear @jkanyi-web, for a semantic reason please use `h2 - h6` tag for the subtitle, `I'm a software developer.`

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +    </div>
- [ ] Dear @jkanyi-web, for a semantic reason please use a `p` tag for a paragraph text.

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +        </div>
- [ ] Dear @jkanyi-web, for a semantic reason every list item should be inside a `ul` tag with each being wrapped with a `li` tag.
> Please use something like 
``` html 
<ul>
  <li>
    <a href="#">
         <img src="images/Vector.png" alt="twitter logo" />   
    </a>
  </li>
  <li>
    <a href="#">
         <img src="images/Vector.png" alt="twitter logo" />   
    </a>
 </li>
</ul>

2022-12-02 18:16 UTC, Tadesse-Alemayehu commented on index.html
> +        <div class="primarytext">Hey There, I'm Kanyi</div>
- [ ] Dear @jkanyi-web, Though your design is good in general, one of the major thing left is your layout. Your layout seems to overflow on `375px` screen size and there exists unnecessary padding and margin to your `body`. Please address this for a better layout. 

### Figma design
![Capture2](https://user-images.githubusercontent.com/69077061/205358840-0ba2b643-5495-4287-be0d-247f2cbd0dc4.PNG)

### Your design 
![Capture](https://user-images.githubusercontent.com/69077061/205358868-3075ad36-4c76-43a0-aa29-b13da4e868fd.PNG)

2022-12-02 22:43 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @jkanyi-web, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 05:44 UTC, jkanyi-web commented
Thank you so much Robertson. May you have a wonderful and blessed weekend.

Regards and God bless.

On Sat, 3 Dec 2022 at 01:43, Robertson Arthur ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳
>
> Hi @jkanyi-web <https://github.com/jkanyi-web>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966>
> Highlights
>
> ✅ No Linter error
> ✅ Correct use of GitHub flow
> ✅ Very descriptive Pull Request(PR)
> ✅ Neat Commit messages
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/1#pullrequestreview-1203202603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5EF62RQVZTAVXFBZN3WLJ3QFANCNFSM6AAAAAASSEPW7E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-03 05:46 UTC, merged