Pull Request for Popup Window for desktop and Mobile
jkanyi-web/Microverse_Portfolio pull request #14
Opened 2023-01-06 13:13 UTC by jkanyi-web

- Added files and images for popup windows on both desktop and mobile
- Updated the  HTML file with a popup window
- Update styles.css file with styling for a popup window
- Add popup window in separate modal.js file for neatness
- Fixed Linter errors

2023-01-06 13:21 UTC, frank1738 reviewed
Hi @jkanyi-web , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pair programming project but I can only see one participant. Your partner should contribute with at least one commit for your project to be valid

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-06 13:35 UTC, jkanyi-web commented
Thanks, Osoro.

On Fri, 6 Jan 2023 at 16:21, Frankline Osoro ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @jkanyi-web <https://github.com/jkanyi-web> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a pair programming project but I can only see one
> participant. Your partner should contribute with at least one commit for
> your project to be valid
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/14#pullrequestreview-1238828945>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5BEL2F2UKKQAVAQZA3WRAL57ANCNFSM6AAAAAATTCGM6U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-06 18:07 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @jkanyi-web, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Linters passing. ✔️
 - Professional README and PR. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 18:07 UTC, leonardodiasb commented on modal.js
> +    </div>
- [ ] Your modal is good and working fine. But on the desktop view it is possible to improve some CSS styling to make it more similar to the Figma template. Kindly add some margin below the popup window to make it centralized on the user's screen, replace the 'X' button to make it on the top right corner of the popup and please try to make the technologies tags centralized on its boxes just like the Figma template. Kindly make those changes to make your popup more professional and similar to the Figma template.
 - Your design:
 - 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/61919617/211072027-d8761ace-0d54-46a8-bfed-c86993ddc62d.png">

 - Figma template:
 - 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/61919617/211072076-6e94b84d-ff2d-4f0c-b0ff-8fc4021182c9.png">

2023-01-07 09:47 UTC, uwadonat approved these changes
## Hi @jkanyi-web,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Good commit messages ✔️
- Well organized and clean project ✔️

![approval](https://user-images.githubusercontent.com/65860678/211144368-8f203c8c-49fa-48a3-b0b4-4d0f080349b3.jpeg)
# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-07 09:52 UTC, jkanyi-web commented
Awesome, thanks!

On Sat, 7 Jan 2023 at 12:47, Donat Uwamahoro ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hi @jkanyi-web <https://github.com/jkanyi-web>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉 Highlights
>
>    - Good commit messages ✔️
>    - Well organized and clean project ✔️
>
> [image: approval]
> <https://user-images.githubusercontent.com/65860678/211144368-8f203c8c-49fa-48a3-b0b4-4d0f080349b3.jpeg>
> Status: Approved ✔️✔️✔️
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100%.
> Please, remember to tag me @uwadonat <https://github.com/uwadonat> in
> your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/14#pullrequestreview-1239647012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5AXFYMOSHHBYRBIRBDWRE3TBANCNFSM6AAAAAATTCGM6U>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-07 10:22 UTC, merged