Updated Second Part of Mobile Responsive Project Under Branch 'sidebranch' and Updated Linter Files
jkanyi-web/Microverse_Portfolio pull request #3
Opened 2022-12-05 17:52 UTC by jkanyi-web

Updated linter files
Updated index.html with 'My Recent Works' part of the Responsive-Mobile project 
Updated style.css with 'My Recent Works' part of the Responsive-Mobile project

2022-12-05 18:18 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 18:18 UTC, Gopxfs commented on index.html
> +            </p>
Please take into account that you should add the "My Recent Works" + "About me" sections from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=w6f1TS1ZWFxWbNt0-0) 😉. Your project currently doesn't contain any of them, I can only see the works `section` header. Kindly make sure to add the requested sections to this branch 😄:

## My Recent Works:
### Figma Design
It should contain the first project:
![image](https://user-images.githubusercontent.com/42799579/205710917-3e0ef505-5548-4041-8abf-c1e0234a3170.png)

Followed by 6 project cards:
![image](https://user-images.githubusercontent.com/42799579/205711030-14041375-26c0-4aae-92d4-8107e3765e3e.png)

### Your design
Currently, you have only a part of the first project:
![image](https://user-images.githubusercontent.com/42799579/205711113-abad7174-fbe2-4dba-aa74-4d5ac3deecfe.png)
![image](https://user-images.githubusercontent.com/42799579/205711180-accc9442-367f-41e6-8e72-7027454933f9.png)

2022-12-05 18:18 UTC, Gopxfs commented on index.html
> +            </p>
## About me
### Figma design
It should contain the following introduction:
![image](https://user-images.githubusercontent.com/42799579/205711766-da299bcb-a1a7-4ebe-978f-6fb2bf2c066a.png)

And a list of your abilities, as displayed below:
![image](https://user-images.githubusercontent.com/42799579/205711894-9a6da155-486b-498f-8752-c41fd1dddb05.png)

### Your design
Currently, there is no about me section on your project.

2022-12-05 18:40 UTC, jkanyi-web commented
Hi Gabriel.
Thanks for the feedback, that part was confusing on what we we're to
actually submit.
It's just that a fellow student said that her project was accepted without
the other sections.
I'll work on it straight away.

Thanks and regards.


On Mon, 5 Dec 2022 at 21:18, Gabriel Fonseca ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ♻️ STATUS: REQUIRED CHANGES ♻️ Hi 👋,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions 🗒️
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @Gopxfs <https://github.com/Gopxfs> in your
> question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/3#discussion_r1039924446>
> :
>
> > +        <section class="about">
>
> +            <h1>My Recent Works</h1>
>
> +            <img src="/Images/Vector.png" alt="straight-line">
>
> +            <div class="placeholder-image"></div>
>
> +
>
> +            <h2>Multi-Post Stories</h2>
>
> +            <p>
>
> +                A daily selection of privately personalized
>
> +                reads; no accounts or sign-ups required.
>
> +                Has been the industry's standard dummy text ever since the 1500s,
>
> +                when an unknown printer took a standard dummy text.
>
> +            </p>
>
>
> Please take into account that you should add the "My Recent Works" +
> "About me" sections from Figma
> <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=w6f1TS1ZWFxWbNt0-0>
> 😉. Your project currently doesn't contain any of them, I can only see
> the works section header. Kindly make sure to add the requested sections
> to this branch 😄:
> My Recent Works: Figma Design
>
> It should contain the first project:
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205710917-3e0ef505-5548-4041-8abf-c1e0234a3170.png>
>
> Followed by 6 project cards:
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205711030-14041375-26c0-4aae-92d4-8107e3765e3e.png>
> Your design
>
> Currently, you have only a part of the first project:
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205711113-abad7174-fbe2-4dba-aa74-4d5ac3deecfe.png>
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205711180-accc9442-367f-41e6-8e72-7027454933f9.png>
> ------------------------------
>
> In index.html
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/3#discussion_r1039928403>
> :
>
> > +        <section class="about">
>
> +            <h1>My Recent Works</h1>
>
> +            <img src="/Images/Vector.png" alt="straight-line">
>
> +            <div class="placeholder-image"></div>
>
> +
>
> +            <h2>Multi-Post Stories</h2>
>
> +            <p>
>
> +                A daily selection of privately personalized
>
> +                reads; no accounts or sign-ups required.
>
> +                Has been the industry's standard dummy text ever since the 1500s,
>
> +                when an unknown printer took a standard dummy text.
>
> +            </p>
>
>
> About me Figma design
>
> It should contain the following introduction:
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205711766-da299bcb-a1a7-4ebe-978f-6fb2bf2c066a.png>
>
> And a list of your abilities, as displayed below:
> [image: image]
> <https://user-images.githubusercontent.com/42799579/205711894-9a6da155-486b-498f-8752-c41fd1dddb05.png>
> Your design
>
> Currently, there is no about me section on your project.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/3#pullrequestreview-1205026078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5EKG6TM4RWG6V2KFETWLYWZBANCNFSM6AAAAAASURZQW4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-07 09:30 UTC, emmiiorji approved these changes
Hi @jkanyi-web, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/205925618-b9420cc0-2916-4049-9935-d14826e4b1a5.gif)

## Good Highlights✔️
- Linter checks are passing
- Good commit messages
- Required change has been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 09:33 UTC, jkanyi-web commented
Hi Emmanuel.
Thank you so much for the positive response and may you have a blessed day
and week ahead.

Regards and God bless.

On Wed, 7 Dec 2022 at 12:30, Emmanuel Orji-Ihuoma ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @jkanyi-web <https://github.com/jkanyi-web>,
> Status: Approved ✅
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> [image: Congrats]
> <https://user-images.githubusercontent.com/20554583/205925618-b9420cc0-2916-4049-9935-d14826e4b1a5.gif>
> Good Highlights✔️
>
>    - Linter checks are passing
>    - Good commit messages
>    - Required change has been implemented
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jkanyi-web/Microverse_Portfolio/pull/3#pullrequestreview-1208071812>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXNG5GTGQWPCD6A4ALBMD3WMBKM5ANCNFSM6AAAAAASURZQW4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-07 09:34 UTC, merged